### ISSUE TITLE
crash on unknown plugin layout

### ISSUE THREAD

**Issue by txoof** [txoof/epd_display#11]
when an unknown layout is found, PaperPi crashes -- instead consider raising a `WARNING` and skip the loading of the module:
```
09:40:56 paperpi:build_plugin_list:382:INFO - [[ Plugin: LMS MacPlay ]]
Traceback (most recent call last):
  File "paperpi.py", line 658, in <module>
    exit_code = main()
  File "paperpi.py", line 639, in main
    plugins = build_plugin_list(config, screen.resolution, cache)
  File "paperpi.py", line 402, in build_plugin_list
    my_config['layout'] = getattr(module.layout, values['layout'])
AttributeError: module 'plugins.lms_client.layout' has no attribute 'twoColumn'```

**Comment by txoof** [comment]
Resolved
