### ISSUE TITLE
crash when lms_client cannot reach network

### ISSUE THREAD

**Issue by txoof** [txoof/epd_display#17]
unhandled exception when network is unreachable in lms_client plugin

```
Sep 14 20:20:01 paperpi paperpi[6936]: 20:20:01 QueryLMS:scan_lms:233:INFO - searching for LMS servers for 5 seconds
Sep 14 20:20:01 paperpi paperpi[6936]: [6937] Failed to execute script 'paperpi' due to unhandled exception!
Sep 14 20:20:01 paperpi paperpi[6936]: Traceback (most recent call last):
Sep 14 20:20:01 paperpi paperpi[6936]:   File "paperpi/paperpi.py", line 859, in <module>
Sep 14 20:20:01 paperpi paperpi[6936]:   File "paperpi/paperpi.py", line 838, in main
Sep 14 20:20:01 paperpi paperpi[6936]:   File "paperpi/paperpi.py", line 409, in build_plugin_list
Sep 14 20:20:01 paperpi paperpi[6936]:   File "/tmp/_MEI0NoqYT/library/Plugin.py", line 254, in update
Sep 14 20:20:01 paperpi paperpi[6936]:     is_updated, data, priority = self.update_function(*args, **kwargs)
Sep 14 20:20:01 paperpi paperpi[6936]:   File "/tmp/_MEI0NoqYT/plugins/lms_client/lms_client.py", line 133, in update_function
Sep 14 20:20:01 paperpi paperpi[6936]:     build_lms()
Sep 14 20:20:01 paperpi paperpi[6936]:   File "/tmp/_MEI0NoqYT/plugins/lms_client/lms_client.py", line 102, in build_lms
Sep 14 20:20:01 paperpi paperpi[6936]:     self.my_lms = QueryLMS.QueryLMS(player_name=player_name, handle_requests_exceptions=True)
Sep 14 20:20:01 paperpi paperpi[6936]:   File "QueryLMS/QueryLMS.py", line 80, in __init__
Sep 14 20:20:01 paperpi paperpi[6936]:   File "QueryLMS/QueryLMS.py", line 173, in set_server
Sep 14 20:20:01 paperpi paperpi[6936]:   File "QueryLMS/QueryLMS.py", line 235, in scan_lms
Sep 14 20:20:01 paperpi paperpi[6936]: OSError: [Errno 101] Network is unreachable```

**Comment by txoof** [comment]
resolved by f0e372f
