### ISSUE TITLE
spotify plugin causes crash when local librespot client is not responding

### ISSUE THREAD

**Issue by txoof** [txoof/epd_display#18]
This appears to be due to a variable assignment issue in the spotify plugin that can be easily resoloved:

```
Oct  2 21:34:03 paperpi paperpi[599]: [623] Failed to execute script 'paperpi' due to unhandled exception!
Oct  2 21:34:03 paperpi paperpi[599]: Traceback (most recent call last):
Oct  2 21:34:03 paperpi paperpi[599]:   File "paperpi/paperpi.py", line 859, in <module>
Oct  2 21:34:03 paperpi paperpi[599]:   File "paperpi/paperpi.py", line 842, in main
Oct  2 21:34:03 paperpi paperpi[599]:   File "paperpi/paperpi.py", line 505, in update_loop
Oct  2 21:34:03 paperpi paperpi[599]:   File "paperpi/paperpi.py", line 460, in update_plugins
Oct  2 21:34:03 paperpi paperpi[599]:   File "/tmp/_MEI1jUQDk/library/Plugin.py", line 254, in update
Oct  2 21:34:03 paperpi paperpi[599]:     is_updated, data, priority = self.update_function(*args, **kwargs)
Oct  2 21:34:03 paperpi paperpi[599]:   File "/tmp/_MEI1jUQDk/plugins/librespot_client/librespot_client.py", line 132, in update_function
Oct  2 21:34:03 paperpi paperpi[599]:     if player_status.status_code == 200:
Oct  2 21:34:03 paperpi paperpi[599]: UnboundLocalError: local variable 'player_status' referenced before assignment
Oct  2 21:34:03 paperpi systemd[1]: paperpi-daemon.service: Main process exited, code=exited, status=1/FAILURE
Oct  2 21:34:03 paperpi systemd[1]: paperpi-daemon.service: Failed with result 'exit-code'.
```

**Comment by txoof** [comment]
resolved with commit 2906cdf249acce779e4724ae88e94ef7348c046d
