### ISSUE TITLE
Crash when BCM driver is not installed

### ISSUE THREAD

**Issue by txoof** [txoof/epd_display#31]
```
21:27:38 paperpi:main:643:INFO - ********** PaperPi 0.2.14.3 Starting **********
21:27:38 paperpi:main:645:DEBUG - configuration:
{'main': {'display_type': 'HD', 'vcom': -1.9, 'max_refresh': 4, 'log_level': 'DEBUG', 'splash': 1, 'rotation': 0, 'daemon': False}, 'xPlugin: decimal binary clock': {'layout': 'layout', 'plugin': 'dec_bin_clock', 'refresh_rate': 30, 'min_display_time': 50, 'max_priority': 2}, 'xPlugin: Weather Adis Ababa': {'layout': 'layout', 'plugin': 'met_no', 'refresh_rate': 300, 'min_display_time': 40, 'max_priority': 2, 'location_name': 'Adis Ababa', 'lat': 9.0, 'lon': 38.75, 'email': 'you@host.diamond'}, 'xPlugin: Moon Phase': {'layout': 'layout', 'plugin': 'moon_phase', 'min_display_time': 30, 'max_priority': 2, 'email': 'you@host.diamond', 'location_name': 'Europe/Amsterdam', 'lat': 52.3, 'lon': 4.9}, 'xPlugin: A Demo Plugin': {'layout': 'layout', 'plugin': 'demo_plugin', 'min_display_time': 30, 'max_priority': 1, 'your_name': 'Slartybartfast', 'your_color': 'chartreuse'}, 'xPlugin: Basic Clock': {'layout': 'layout', 'plugin': 'basic_clock', 'refresh_rate': 30, 'min_display_time': 50, 'max_priority': 2}, 'xPlugin: XKCD Comic Plugin': {'layout': 'layout', 'plugin': 'xkcd_comic', 'refresh_rate': 1200, 'min_display_time': 120, 'max_x': 800, 'max_y': 600, 'resize': 0, 'max_retries': 10, 'max_priority': 2}, 'xPlugin: New Yorker Comic': {'layout': 'layout', 'plugin': 'newyorker', 'day_range': '5 # number of past days to choose from', 'refresh_rate': 120, 'min_display_time': 60, 'max_priority': 2}, 'xPlugin: Librespot': {'layout': 'layout', 'plugin': 'librespot_client', 'refresh_rate': 10, 'max_priority': 0, 'min_display_time': 15, 'player_name': 'SpoCon-Spotify', 'idle_timeout': 10}, 'xPlugin: Reddit Quotes': {'layout': 'layout', 'plugin': 'reddit_quote', 'refresh_rate': 100, 'min_display_time': 50, 'max_priority': 2, 'max_length': 144}, 'xPlugin: LMS - Your Player Name': {'layout': 'layout', 'plugin': 'lms_client', 'player_name': 'Your Player Name', 'refresh_rate': 5, 'min_display_time': 30, 'max_priority': 0, 'idle_timeout': 15}, 'xPlugin: Word Clock': {'layout': 'layout', 'plugin': 'word_clock', 'refresh_rate': 125, 'min_display_time': 255, 'max_priority': 2}, 'Plugin: XKCD Comic Plugin': {'layout': 'layout', 'plugin': 'xkcd_comic', 'refresh_rate': 1200, 'min_display_time': 120, 'max_x': 800, 'max_y': 600, 'resize': 0, 'max_retries': 10, 'max_priority': 2}, 'Plugin: Reddit Quotes': {'layout': 'layout', 'plugin': 'reddit_quote', 'refresh_rate': 100, 'min_display_time': 50, 'max_priority': 2, 'max_length': 144}, '__cmd_line': {'list_plugins': False}}
21:27:38 Screen:_load_hd:399:DEBUG - configuring IT8951 epd
Traceback (most recent call last):
  File "paperpi/paperpi.py", line 729, in <module>
  File "paperpi/paperpi.py", line 648, in main
  File "paperpi/paperpi.py", line 322, in setup_display
  File "epdlib/Screen.py", line 226, in __init__
  File "epdlib/Screen.py", line 38, in new_f
  File "epdlib/Screen.py", line 316, in epd
  File "epdlib/Screen.py", line 406, in _load_hd
  File "IT8951/display.py", line 215, in __init__
RuntimeError: Problem importing EPD interface. Did you build the backend with "pip install ./" or "python setup.py build_ext --inplace"?
[4255] Failed to execute script 'paperpi' due to unhandled exception!
```

**Comment by txoof** [comment]
This can likely be handled with a try/except around the init of the screen around ll322.

**Comment by txoof** [comment]
This crash was due to a bad build environment. The system-wide IT8951 driver isn't needed any longer thanks to the Greg Meyer 8951 module.
