### ISSUE TITLE
new yorker plugin crash

### ISSUE THREAD

**Issue by txoof** [txoof/epd_display#44]
```
17:48:10 Block:_calc_maxchar:923:DEBUG - maximum characters per line: 148
17:48:10 Block:_text_formatter:939:DEBUG - formatting string: NONE
17:48:10 Block:_text2image:983:DEBUG - text size: (16, 11)
17:48:10 Block:_text2image:1030:DEBUG - paste coordinates: (5, 5)
Traceback (most recent call last):
  File "paperpi/paperpi.py", line 729, in <module>
  File "paperpi/paperpi.py", line 682, in main
  File "paperpi/paperpi.py", line 431, in build_plugin_list
  File "/tmp/_MEISqIwwY/library/Plugin.py", line 254, in update
    is_updated, data, priority = self.update_function(*args, **kwargs)
  File "/tmp/_MEISqIwwY/plugins/newyorker/newyorker.py", line 134, in update_function
    success, my_data, day_range = fetch_comic(day_range)
  File "/tmp/_MEISqIwwY/plugins/newyorker/newyorker.py", line 95, in fetch_comic
    if day_range > len(feed.entries):
TypeError: '>' not supported between instances of 'str' and 'int'
[8750] Failed to execute script 'paperpi' due to unhandled exception!
```

**Comment by txoof** [comment]
This may be due to an misplaced comment line in sample configuration file

**Comment by txoof** [comment]
Issue is [here](https://github.com/txoof/epd_display/blob/749578316522eb6bbc7017917e8f288b360cc377/paperpi/config/paperpi.ini#L129-L135)

The root is within the new yorker plugin its self.
